name: flashback_cam
description: "Capture every moment, even the ones you almost missed, with Flashback Cam – the innovative pre-roll camera app that ensures you never lose a memory!"
publish_to: "none"
version: 1.0.14+17

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  shared_preferences: ^2.0.0
  path_provider: ^2.0.0
  video_player: '>=2.9.2'
  provider: ^6.0.0
  intl: 0.20.2
  share_plus: ^10.0.0
  permission_handler: ^11.3.1
  path: ^1.9.0
  in_app_purchase: ^3.2.0
  google_mobile_ads: ^6.0.0
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/flashback_cam_icon.png
  remove_alpha_ios: true
